apiVersion: skaffold/v1
kind: Config
metadata:
  name: golang-reference-app
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: json0/go-reference-app
deploy:
  statusCheckDeadlineSeconds: 300 # Checks the deployment health using the kubectl rollout status
  kubectl:
    manifests:
    - deploy/*.yaml # Deploys all manifest files in the deploy directory

profiles:
  - name: quickcheck
    test:
      - image: json0/go-reference-app
        structureTests:
          - './structure-test/container-test.yaml'
