apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-wiki
  namespace: jason-lab
spec:
  selector:
    matchLabels:
      app: golang-wiki
  replicas: 3
  template:
    metadata:
      labels:
        app: golang-wiki
    spec:
      containers:
      - name: golang-wiki
        image: json0/go-reference-app:honey2.3
        env:
          - name: HONEYCOMB_API
            valueFrom:
              secretKeyRef:
                name: honeycomb
                key: api
        ports:
        - containerPort: 8080
